name: MultiVoteListener
author: bmack94
version: ${project.version}
main: de.bmack.MultiVoteListener.MultiVoteListener
description: Multiple Service Vote Listener for Votifier
api-version: 1.18

authors: [ bmack94 ]
depend: [ Votifier, Vault ]
softdepend: [ PlayerPoints ]

commands:
   mvote:
     description: MultiVoteListener Command Interface
     usage: /mvote
   votepokal:
     description: Gibt einem Spieler einen Votepokal
     usage: /votepokal
     permission: blockminers.votepokal
permissions:
  blockminers.votepokal:
    description: Erlaubt das Nutzen des Votepokal-Commands
    default: false